<a href="https://colab.research.google.com/github/codebysahil/PythonNotebooks/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Numpy Arrays
Numpy array can be created of any dimensions like 1 d , 2-d ----- similarly 25-d or n-d  and you can create numpy array of your data type as required for example interger array string array

In [9]:
import numpy as np
a = np.array([1,2,3]) # 1 d numpy array or vectors
print(a)
print(type(a))
print("***********************************")
b = np.array([[1,2,4],[3,6,7]]) # 2 d numpy arrays or matrix
print(b)
print("***********************************")
c = np.array([[1,2,3],[6,7,8],[9,10,11]]) # 3 d numpy  arrays or tensor
print(c)

[1 2 3]
<class 'numpy.ndarray'>
***********************************
[[1 2 4]
 [3 6 7]]
***********************************
[[ 1  2  3]
 [ 6  7  8]
 [ 9 10 11]]


In [14]:
d=np.array([1,2,4],dtype=float)
print(d)
bool_array=np.array([1,0,100],dtype=bool)
print(bool_array)
complex_d=np.array([1,2,4],dtype=complex)
print(complex_d)

[1. 2. 4.]
[ True False  True]
[1.+0.j 2.+0.j 4.+0.j]


np.arange function -- to create arrays similar to range function in python


In [17]:
# arnage function

e=np.arange(1,11)
e_1=np.arange(1,11,3)
print(e)
print(e_1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]


In [19]:
# reshape function used with arange

e_2 =np.arange(1,13).reshape(3,4)
print(e_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
# initializing the numpy array
# np.ones
# np.zeroes
# np.random

In [ ]:
# creating an numpy array 5 methods
# np.array()
# np.arange()
# np.ones
# np.zeroes
# np.random
# np.linspace
# np.identity



In [21]:
pip install np

  Preparing metadata (setup.py) ... done
  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13658 sha256=55ecbfadfb0d2f54256443c39b4e5b64f3c1617091b24d5571715c5d692fa30b
  Stored in directory: /root/.cache/pip/wheels/19/20/42/6ee214e617f78123903f603524d662ac6fa14154c3027fd992
Successfully built np


In [26]:
import numpy as np1
arr1 =np1.array([1,2,4,5,5,5,5,5,5,5,5,5])
print(arr1)
print(type(arr1))
print(arr1.shape) # single dimensional array

arr2=arr1.reshape(3,4) # 2 dimensional array 3 rows and 4 colums
print("--------------------------------------------")
print(arr2)


[1 2 4 5 5 5 5 5 5 5 5 5]
<class 'numpy.ndarray'>
(12,)
--------------------------------------------
[[1 2 4 5]
 [5 5 5 5]
 [5 5 5 5]]


In [27]:
one_array=np.ones((3,4))
print(one_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
# identity matrix

identity_arr= np.identity(2)
print(identity_arr)
print("--------------------------------------------------------------------------------------")
identity_arr1= np.eye(3)
print(identity_arr1)

[[1. 0.]
 [0. 1.]]
--------------------------------------------------------------------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# some other methods available in numpy for arrays
b1 = np.array([[1,2,4],[3,6,7]])
print("Arrays:\n", b1)
print("Shape:\n", b1.shape)

print("number of dimensions:\n",b1.ndim)
print("size of array:\n",b1.size)
print("data type:\n",b1.dtype)
print("ItemSize:\n",b1.itemsize)

Arrays:
 [[1 2 4]
 [3 6 7]]
Shape:
 (2, 3)
number of dimensions:
 2
size of array:
 6
data type:
 int64
ItemSize:
 8


In [35]:
# numpy vectorized operations
arr1 =np.array([1,2,3,4,5])
arr2= np.array([10,20,30,40,50])

### element wise addition
print("addition"," ",arr1+arr2)
### element wise subsraction
print("Substraction"," ",arr1-arr2)
### element wise multiplication
print("Multiplication"," ",arr1*arr2)
### element wise subsraction
print("Substraction"," ",arr2-arr1)
### element wise subsraction
print("Substraction"," ",arr2-arr2)



addition   [11 22 33 44 55]
Substraction   [ -9 -18 -27 -36 -45]
Multiplication   [ 10  40  90 160 250]
Substraction   [ 9 18 27 36 45]
Substraction   [0 0 0 0 0]


In [40]:
## Universal functions that apply to entire array element but it is applied element wise
## square root
print("square-root"," " ,np.sqrt(arr1))
print("sine"," " ,np.sin(arr1))
print("exponential"," " ,np.exp(arr1))
print("natural log"," " ,np.log(arr1))




square-root   [1.         1.41421356 1.73205081 2.         2.23606798]
sine   [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
exponential   [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
natural log   [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [54]:
## Array Slicing and indexing

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0][2])
print("***********")
print(arr[0,2])
print(arr[0:2])
print(arr[0:2,1:])



3
***********
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [52]:
arr1= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr1)
print("after slicing")
print(arr1[1:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
after slicing
[[ 6  7]
 [10 11]]


In [53]:
# Modify array elements
print(arr)
arr[0,0]=100
print("after modification", arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
after modification [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
## statistical concept
#### normalization to have a mean of 0 and sd =1

### to calculate mean median and deviation

## Logical Operations

